version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    environment:
      STRATEGY: 'simplearbitrage'
      MARKET: 'BTC-USD'
      SPREAD: '1'
      ORDER_SIZE: '1'
      EXCHANGES: 'coinbasepro,bitfinex'
